version: '3.8'

services:
  postgis:
    image: imresamu/postgis
    container_name: postgis
    ports:
      - 5432:5432
    platform: linux/arm64
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_pwd
    volumes:
      - postgis_data:/var/lib/postgresql/data
    secrets:
      - postgres_pwd

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD_FILE: /run/secrets/passwd_secret
    volumes:
      - type: bind
        source: ./pgadmin
        target: /var/lib/pgadmin
    secrets:
      - passwd_secret

volumes:
  postgis_data:
    name: postgis_data
  pgadmin:
  postgres:

secrets:
  passwd_secret:
    file: ./pgadmin_pwd.txt
  postgres_pwd:
    file: ./postgres_pwd.txt
